#!/bin/bash
if [ -n "$1" ]; then
 if [ -f "$1" ]; then
 echo $1 '文件已经存在，不能重复创建'
 else
 echo '#!/bin/bash' > $1
 echo '# -*- coding: UTF-8 -*-' >> $1
 echo '#===============================================================================' >> $1
 echo "#Usage: " >>$1
 echo "#Description: " >>$1
 time=`date`
 echo '#Generate time: '$time>>$1 
 echo '#Main program' >> $1
 echo '#===============================================================================' >> $1
 chmod +x $1
 echo $1 '文件创建成功'
 fi
else
 echo '请添加新建 Python 文件名参数'
fi
