#!/bin/csh -f
#fundy 20200701
#running under ori dir
#tenv format
#1. station ID (SSSS)
#2. date (yymmmdd)
#3. decimal year
#4. Modified Julian Day (MJD)
#5. GPS week
#6. day of GPS week (Sunday = 0, Saturday = 6)
#7. delta e (m)
#8. delta n (m)
#9. delta v (m)
#10. antenna height (m)
#11. sigma e (m)
#12. sigma n (m)
#13. sigma v (m)
#14. correlation en
#15. correlation ev
#16. correlation nv 
#paste .name .ymd .yf .mjd .gpsw _0.ts0 _1.ts0 _2.ts0 .zero .sixp 
#pfiles format
#    EPOCH  SITE TIE  LONGITUDE       LATITUDE     HEIGHT       Se    Sn    Su     COVen    COVeu    COVnu
#                     (Deg)           (Deg)       (m)              (mm)                               
# 2012.0055 XZGZ .   84.071077946   32.292197422  4423.2879     1.5   0.7   2.9   -0.050    0.058   -0.208
#     1		  2	  3		 4				 5			 6			 7	   8	9	    10		  11	  12
#
mkdir tenv
cd pfiles
splitts_tenv
foreach file (`ls *.yf`)
 	set site=`basename $file .yf`
	awk '{print int($1),int(365*($1-int($1))+0.5)}' $file> $site.ydoy
	awk '{print $10,$11,$12}' ${site}.pfiles> $site.sixp
 	set num=`wc -l $file|awk '{print $1}'`
	set count = 1
	set refe=`awk '{if(FNR=="'"$count"'")print $0}' ${site}_0.ts`
	set refn=`awk '{if(FNR=="'"$count"'")print $0}' ${site}_1.ts`
	set refv=`awk '{if(FNR=="'"$count"'")print $0}' ${site}_2.ts`
	while ($count <= $num)
		set e=`awk '{if(FNR=="'"$count"'")print $0}' ${site}_0.ts`
		set n=`awk '{if(FNR=="'"$count"'")print $0}' ${site}_1.ts`
		set v=`awk '{if(FNR=="'"$count"'")print $0}' ${site}_2.ts`
		set rese=`awk -v aa=$e -v bb=$refe 'BEGIN{printf "%.6f\n",aa-bb}'`
		set resn=`awk -v aa=$n -v bb=$refn 'BEGIN{printf "%.6f\n",aa-bb}'`
		set resv=`awk -v aa=$v -v bb=$refv 'BEGIN{printf "%.6f\n",aa-bb}'`
		echo $site>>${site}.name
		echo $rese>>${site}_0.ts0
		echo $resn>>${site}_1.ts0
		echo $resv>>${site}_2.ts0
		echo 0>>${site}.zero
		set ydoy=`awk '{if(FNR=="'"$count"'")print $0}' $site.ydoy`
		ydoy2ymd $ydoy|tr "[a-z]" "[A-Z]">>$site.ymd
		#set ymd=`ydoy2ymd $ydoy`
		#ymd2gweek $ymd>>$site.gpsw
		set date0=`ydoy2date_hector $ydoy`
		set date1=`echo $date0|awk '{print $1,$2,$3}'`
		yyyymmdd2gweek $date1>>$site.gpsw
		date2mjd $date0 |grep "MJD"|awk '{printf "%d\n",$3}'>> $site.mjd
		@ count++
	end
	
	paste ${site}.name $site.ymd $site.yf $site.mjd $site.gpsw ${site}_0.ts0 ${site}_1.ts0 ${site}_2.ts0 ${site}.zero ${site}.senu ${site}.sixp  >${site}.tenv
#cat ${site}.tenv|head -n5
	rm ${site}*.ts0
	rm ${site}.yf
	rm ${site}*.ts
	rm ${site}.name
	rm ${site}.ymd
	rm ${site}.mjd
	rm ${site}.gpsw
	rm ${site}.zero
	rm ${site}.sixp
	rm ${site}.ydoy
	rm ${site}.senu
#delete repeat time
	sort -k 3 -nu ${site}.tenv -o ${site}.tenv
	echo ${site}
end
mv -f *.tenv ../tenv
cd ..



