#!/bin/csh -f
#fundy 20200701
#split .ts file into yearfraction,x,y,z(mm). And change the init from deg to mm

foreach file (`ls *.ts`)
	set site=`basename $file .pfiles.ts`
	awk '{print $1}' $file >>$site.yf
#E
	awk '{printf("%18.3f\n",$2*1000*6367445/180*3.14159265)}' $file >>${site}_0.ts
#N
	awk '{printf("%18.3f\n",$3*1000*6367445/180*3.14159265)}' $file >>${site}_1.ts
#U
	awk '{printf("%15.3f\n",$4*1000)}' $file >>${site}_2.ts
end
echo "spliting completed"

