#!/bin/csh -f
#fundy 20200701
#split .pfiles file into yearfraction,x,y,z(m). And change the init from deg to m
#WGS84 Parameters


foreach file (`ls *.pfiles`)
	set site=`basename $file .pfiles`
#get M/N
	set b=`awk '{print $5}' $file`
	set mn=(`cal_MN.py $b`)
	set m = ${mn[1]}
	set n = ${mn[2]}
	awk '{print $1}' $file >>$site.yf
#E
	awk '{printf("%12.6f\n",$4*"'$n'"/180*3.14159265)}' $file >>${site}_0.ts
#N
	awk '{printf("%12.6f\n",$5*"'$m'"/180*3.14159265)}' $file >>${site}_1.ts
#U
	awk '{printf("%12.6f\n",$6)}' $file >>${site}_2.ts
#Senu
	awk '{printf("%2.6f	%2.6f	%2.6f\n",$7/1000,$8/1000,$9/1000)}' $file >>${site}.senu
end

