#!/bin/tcsh
set tenv = $1
set site = `basename $tenv .tenv`
echo $tenv $site
awk '{printf "%8.4f %6.3f %6.3f\n",$3,$7*1000,$11*1000}' $tenv > ${site}_0.gmt
awk '{printf "%8.4f %6.3f %6.3f\n",$3,$8*1000,$12*1000}' $tenv > ${site}_1.gmt
awk '{printf "%8.4f %6.3f %6.3f\n",$3,$9*1000,$13*1000}' $tenv > ${site}_2.gmt
